### ISSUE TITLE
Add translation to PT-BR

### ISSUE THREAD

**Issue by Kerooker** [Kerooker/rpg-npc-generator#34]

**Comment by AlbertoDoc** [comment]
Hi, how i can help in this issue? there are some file that contain the strings to be translated?

**Comment by Kerooker** [comment]
Hi!
Thanks for reaching out!

Let me commit what I'm currently working on, so you can take a look.

**Comment by Kerooker** [comment]
I'm working at the branch `feature/34-add-translation-to-pt-br`, currently as a draft pr at #47 

There are some localization files at specific folders. I already translated the entire `values` folder (`values-pt`), and I'm working on `raw-pt`, which is a little bit harder as the lists are very large

**Comment by Kerooker** [comment]
Currently,
`npc_child_professions` and `npc_motivations` are translated.
I won't translate `npc_names`, as I don't believe it makes a lot of sense.

Currently missing `npc_nicknames`, `npc_personality_trait` and `npc_professions`. Let me know what you're willing to work on, so we don't clash what we're doing!

**Comment by Kerooker** [comment]
One thing we can do is that instead of literally translating, we can find another good list of values aprox. the same size and use that instead. It might be easier than translating value by value.

As long as it's diverse enough and big enough for randomness to be good, I'm OK with it!

**Comment by AlbertoDoc** [comment]
I'll do ```npc_professions```. If i take another i notice here.

A doubt, in the profession "actor" is to be translated as
```Ator```
or
```Ator/Atriz```
or
```Ator
Atriz
```

**Comment by Kerooker** [comment]
Honestly, I'm not sure.

It's not trivial to change it based on gender changing, so we'll have to
pick an option.

For nicknames, I think I'll do

The Brave -> O Corajoso

And let the user know how to change it to the female alterntive. Just
because "O/A Corajoso/A" might be weird. But I'm not sure what is better.

What do you think?

**Comment by AlbertoDoc** [comment]
I think that just keep the male option is better than "O/A Corajoso/A".

**Comment by Kerooker** [comment]
Ok, let's do that for now.

I'll see how to change dynamically later, and adapt accordingly
