### ISSUE TITLE
Lost NPC details after 3.2.2 upgrade

### ISSUE THREAD

**Issue by Cullly** [Kerooker/rpg-npc-generator#52]
**Describe the bug**
I used this app a while back to create a number of NPCs. I don't remember the exact version of the app I was using but it was at least a couple months old. Recently, I upgraded the app to version 3.2.2. After the upgrade all my NPCs lost their details, only their names remain.

**To Reproduce**
1. Have NPCs with details saved in the app in the old format. 
2. Download and install the latest version (3.2.2).
3. Open the app.
4. Click on one of your NPCs.
5. See all of their details are blank.

**Expected behavior**
After upgrading, I expected all my previous character details to carry over to the new version.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S7
 - OS: Android 8.0.0; SM-G930V Build/R16NW
 - Browser: Google Chrome
 - Version: 79.0.3945.93

**Comment by Kerooker** [comment]
As explained via email:

This was unfortunately caused by an error during the migration to the newest version, and unfortunately you had that happen to you.

I'll not fix this issue, as it only affect a few people that were still in the old version.
